var keys = [
  "Key of C",
  "Key of F",
  "Key of B Flat",
  "Key of E Flat",
  "Key of A Flat",
  "Key of D Flat",
  "Key of G Flat",
  "Key of C Flat",
  "Key of G",
  "Key of D",
  "Key of A",
  "Key of E",
  "Key of B",
  "Key of F Sharp",
  "Key of C Sharp",
];
var scale = [
  "Major",
  "Minor",
  "Pentatonic Major",
  "Pentatonic Minor",
  "Ionian",
  "Dorian",
  "Phrygian",
  "Lydian",
  "Lydian Minor",
  "Mixolydian",
  "Aeolian",
  "Locrian",
  "Diatonic",
  "Diminished"
];
